export const toggle: string;
export const toggleLabel: string;
export const toggleInput: string;
export const Green: string;
export const green: string;
export const Blue: string;
export const blue: string;
export const Red: string;
export const red: string;
